apiVersion: apps/v1
kind: Deployment
metadata:
  name: oss-fe-proxy
  namespace: oss-fe-proxy
  labels:
    app: oss-fe-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oss-fe-proxy
  template:
    metadata:
      labels:
        app: oss-fe-proxy
    spec:
      serviceAccountName: oss-fe-proxy
      containers:
      - name: oss-fe-proxy
        image: reg.imvictor.tech/library/oss-fe-proxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        - containerPort: 9181
          name: metrics
        - containerPort: 8443
          name: webhook
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WEBHOOK_ENABLED
          value: "true"
        - name: WEBHOOK_PORT
          value: "8443"
        - name: WEBHOOK_SERVICE_NAME
          value: "oss-fe-proxy-webhook"
        - name: WEBHOOK_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WEBHOOK_CERT_PATH
          value: "/tmp/webhook-certs/tls.crt"
        - name: WEBHOOK_KEY_PATH
          value: "/tmp/webhook-certs/tls.key"
        - name: WEBHOOK_CA_PATH
          value: "/tmp/webhook-certs/ca.crt"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1"
          limits:
            memory: "4096Mi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9181
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9181
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-logs
          mountPath: /var/log/nginx
        - name: webhook-certs
          mountPath: /tmp/webhook-certs
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-logs
        emptyDir: {}
      - name: webhook-certs
        secret:
          secretName: oss-fe-proxy-webhook-certs
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - oss-fe-proxy
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: oss-fe-proxy
  namespace: oss-fe-proxy
  labels:
    app: oss-fe-proxy
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 9181
    targetPort: 9181
    protocol: TCP
    name: metrics
  selector:
    app: oss-fe-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: oss-fe-proxy-headless
  namespace: oss-fe-proxy
  labels:
    app: oss-fe-proxy
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 9181
    targetPort: 9181
    protocol: TCP
    name: metrics
  selector:
    app: oss-fe-proxy