apiVersion: apps/v1
kind: Deployment
metadata:
  name: oss-fe-proxy
  namespace: oss-fe-proxy
  labels:
    app: oss-fe-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oss-fe-proxy
  template:
    metadata:
      labels:
        app: oss-fe-proxy
    spec:
      serviceAccountName: oss-fe-proxy
      containers:
      - name: oss-fe-proxy
        image: reg.imvictor.tech/library/oss-fe-proxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            memory: "128Mi"
            cpu: "1"
          limits:
            memory: "512Mi"
            cpu: "4"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-logs
          mountPath: /var/log/nginx
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-logs
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - oss-fe-proxy
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: oss-fe-proxy
  namespace: oss-fe-proxy
  labels:
    app: oss-fe-proxy
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: oss-fe-proxy